CREATE PROCEDURE addIcm
	@ICMID int,
	@UserName NVARCHAR(25),
	@Name NVARCHAR(30),
	@Age INT,
	@GENDER BIT,
	@YOE DATE,
	@EMAIL NVARCHAR(100)

AS
INSERT INTO InventoryControlManager VALUES (1,@ICMID,@UserName,@Name,@Age,@GENDER,@YOE,@EMAIL)